networks:
  app-network:
    driver: bridge

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    networks:
      - app-network
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data"
    volumes:
      - consul_data:/consul/data

  apigateway:
    image: 19122002/test_app:apigateway
    container_name: apigateway
    networks:
      - app-network
    ports:
      - "9000:9000"

  userapi:
    image: 19122002/test_app:userapi
    container_name: userapi
    networks:
      - app-network
    ports:
      - "9005:9005"
  
volumes:
  consul_data: