networks:
  app-network:
    driver: bridge

services:
  gateway_service:
    image: 19122002/test_app:apigateway
    container_name: apigateway
    networks:
      - app-network
    ports:
      - "9000:9000"

  user_service:
    image: 19122002/test_app:userapi
    container_name: user_service
    networks:
      - app-network
    ports:
      - "9005:9005"