networks:
  app-network:
    driver: bridge

services:
  consul:
    image: consul:1.15.4
    container_name: emon_consul
    networks:
      - app-network
    ports:
      - "8500:8500"
    environment:
      - CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data"
    volumes:
      - consul_data:/consul/data
      - ./consul/server1.json:/consul/config/server1.json
      - ./consul/acls/:/consul/config/acls/

  postgres: 
    image: postgres:17-alpine
    container_name: emon_postgres
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/postgres_data/data

  redis: 
    image: redis:7.4.1-alpine
    container_name: emon_redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  cdnapi:
    image: 19122002/test_app:cdn
    container_name: emon_cdnapi
    networks:
      - app-network
    ports:
      - "3000:80"
    volumes:
      - cdn_data:/app/uploads
  
volumes:
  consul_data:
  postgres_data:
  cdn_data: